name: Daily Follow-up Reminders

# Schedule: Run daily at 9:00 AM UTC
on:
  schedule:
    - cron: '0 9 * * *'  # 9:00 AM UTC every day
  workflow_dispatch:  # Allow manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Send daily reminders
        env:
          SQLALCHEMY_DATABASE_URI: ${{ secrets.DATABASE_URL }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_DEFAULT_SENDER: ${{ secrets.MAIL_DEFAULT_SENDER }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python send_reminders_cron.py
      
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Daily Reminders Failed',
              body: 'The daily reminder job failed. Please check the workflow logs.',
              labels: ['bug', 'automated']
            })
